sonata_admin:
    title: 'Shop Bot'
    title_logo: 'Admin'
    search: false

sonata_block:
    blocks:
        # enable the SonataAdminBundle block
        sonata.admin.block.admin_list:
            contexts: [admin]